language: cpp
os: osx
osx_image: xcode10
compiler: clang
branches:
  except:
    - /^continuous-/

install:
  - git config --global protocol.version 1
  - brew remove --force $(brew list) --ignore-dependencies 
  - brew update
  - until brew install sdl_mixer libpng libjpeg freetype glew openssl@1.1 git libyaml; do true; done
  - brew unlink cmake || true
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/74d54460d0af8e21deacee8dcced325cfc191141/Formula/cmake.rb
  - brew pin cmake

before_script:
  - mkdir build
  - cd build
  - cmake -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl@1.1" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-w" -DCMAKE_C_FLAGS="-w" ..

script:
  - make
  - export TRAVIS_TAG=continuous-${TRAVIS_BRANCH}
  - git tag ${TRAVIS_TAG} || true

before_deploy:
  - git clone https://github.com/auriamg/macdylibbundler/
  - cd macdylibbundler
  - git checkout 9cf053f8b399512e12d7931fa24f466057e58044
  - make
  - cd ..
  - macdylibbundler/dylibbundler -od -b -x clonk.app/Contents/MacOS/clonk -d clonk.app/Contents/libs/
  - ls
  - tar -cvzf LegacyClonk-mac.tar.gz c4group clonk.app

deploy:
  provider: releases
  api_key:
    secure: P/8crTgVwHK5+e/1bzEMDnjN7ZOFYun9fh3eFCVZUmTJVo3g2+8n4C5thZ49bZdEO75sATY0o+xUtG4cKmop4fU3m06MHvc7soQOsv+2J5l9plnVRZBjhlNaOYX/OTmZKg8+2dk3T/auG9EO3EgJw3HB+5CPxbNMRKH8Y2BC3MKh3hB4J6VUxkA7vqOCq2IqCZ2yHWmFS1LZ4lEX5Y0oe+9PA7L1Gkk/raYRomh+HXtRvLRhEdsX6Z/cNW/GaLrcIK3yhuxC22+P9a67q4CGD6V6sXuR++vOKYIL9moLG07Fns64QJRmUVushkxIX0gnAMK/ZZ9/fEZa/Bf2xmYMdOdPh/mll700iNc2I9nxB0r+KJPgLRJGJWFTYqJtPF0jDaM1/REGQ8ygIkywxkQfuIZ6klnMjLW5hmQE0K6jd4WGKJLQmVrpd9opBEIVpNITdJQSSxoxdsw2TXvCujCJGnllrEauVRiSDbYXToGJKQanoL+/RemKqP/T68IA3ay2/pUCA8hrkEoCpOTj7DDjByWAxKIqmRQGDlUa0EiKlKEiq4Wsg2k+HxrxuODws0W9o4g+mL1SXErzEvGt4apG9s+QHhKVl7iMqvkv5wNQDxk9elJaizDuTLhfAHDMY1VzU3/mUwamm51r27mXVU29UCYpvUpGM9q7GSN66utYCEg=

  file: LegacyClonk-mac.tar.gz
  on:
    repo: legacyclonk/LegacyClonk
    tags: true

  all_branches: true
  skip_cleanup: true
  overwrite: true
  draft: false
  prerelease: true
