#!/bin/bash
echo "CMAKE_CONFIGURE_ARGS=-DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_DEVELOPER_MODE=On -DCMAKE_TOOLCHAIN_FILE=$PWD/autobuild/gcc13_20.04.cmake" >> $GITHUB_ENV
echo "CMAKE_BUILD_ARGS=-- -j$(nproc)" >> $GITHUB_ENV
