//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by editor.rc
//
#define IDD_LEAGUEPW                    133
#define IDD_LEAGUESELECT                134
#define IDB_BUTTON                      1006
#define IDB_COM                         1008
#define IDB_CONTROL                     1009
#define IDB_DECOGAME                    1011
#define IDB_DECOWEATHER                 1012
#define IDB_ICONSCENARIO                1013
#define IDB_IDCTRLBUTTONS               1014
#define IDB_ITEMICONS                   1015
#define IDB_ITEMSTATE                   1016
#define IDB_PALETTE                     1018
#define IDB_PAPER                       1019
#define IDB_SPLASH                      1036
#define IDB_TABICON                     1037
#define IDC_CHECKPXSGFX                 1290
#define IDC_CHECKNOADDBLT               1291
#define IDC_CHECKNOCLRFADE              1292
#define IDC_RADIOGFX0                   1293
#define IDC_RADIOGFX1                   1294
#define IDC_RADIOGFX2                   1295
#define IDC_EDITBLITOFFS                1296
#define IDC_CHECKMANUALCLIP             1297
#define IDC_EDITTEXIN                   1298
#define IDC_STATICBLITOFF               1301
#define IDC_STATICTEXINDENT             1302
#define IDC_SPINBLITOFF                 1303
#define IDC_SPINTEXINDENT               1304
#define IDC_STATICPWD                   1306
#define IDC_EDITPLRNAME                 1307
#define IDC_STATICPLRNAME               1308
#define IDC_LISTLGS                     1317
#define IDC_FRAMEKEYFILE                1318
#define IDC_BTNRUNGFXPROC               1319
#define IDC_COMBORESOLUTION             1322
#define IDC_CHECKSHOWALLRES             1323
#define IDC_STATICLANGINFO              1324
#define IDC_CHECKPROMPT                 1326
#define IDC_STATIC_SWITCH               1327
#define IDC_EDITSTATUS                  1328
#define IDC_BITMAPCLIMATE               2001
#define IDC_BITMAPCTRL1                 2002
#define IDC_BITMAPCTRL10                2003
#define IDC_BITMAPCTRL11                2004
#define IDC_BITMAPCTRL12                2005
#define IDC_BITMAPCTRL2                 2008
#define IDC_BITMAPCTRL3                 2009
#define IDC_BITMAPCTRL4                 2010
#define IDC_BITMAPCTRL5                 2011
#define IDC_BITMAPCTRL6                 2012
#define IDC_BITMAPCTRL7                 2013
#define IDC_BITMAPCTRL8                 2014
#define IDC_BITMAPCTRL9                 2015
#define IDC_BITMAPDESC                  2016
#define IDC_BITMAPEARTHQUAKES           2017
#define IDC_BITMAPMETEORITES            2018
#define IDC_BITMAPRAIN                  2019
#define IDC_BITMAPSEASON                2020
#define IDC_BITMAPTHUNDERSTORM          2021
#define IDC_BITMAPTIMEADVANCE           2022
#define IDC_BITMAPVOLCANOES             2023
#define IDC_BITMAPWIND                  2024
#define IDC_BUTTONACTIVATE              2025
#define IDC_BUTTONBLOCK1                2035
#define IDC_BUTTONBLOCK2                2036
#define IDC_BUTTONBLOCK3                2037
#define IDC_BUTTONBLOCK4                2038
#define IDC_BUTTONDELETE                2039
#define IDC_BUTTONEDITORBITMAP          2042
#define IDC_BUTTONEDITORMUSIC           2043
#define IDC_BUTTONEDITORRICHTEXT        2044
#define IDC_BUTTONEDITORSCRIPT          2045
#define IDC_BUTTONEDITORSOUND           2046
#define IDC_BUTTONEDITORTEXT            2047
#define IDC_BUTTONEDITORZIP             2048
#define IDC_BUTTONEND                   2049
#define IDC_BUTTONEXTEND                2050
#define IDC_BUTTONNEW                   2055
#define IDC_BUTTONPROPERTIES            2057
#define IDC_BUTTONRENAME                2058
#define IDC_BUTTONRESETCTRLKEY          2060
#define IDC_BUTTONSANIMALS              2062
#define IDC_BUTTONSCREW                 2063
#define IDC_BUTTONSENVIRONMENT          2064
#define IDC_BUTTONSGOALS                2065
#define IDC_BUTTONSINEARTH              2066
#define IDC_BUTTONSMAGIC                2067
#define IDC_BUTTONSNESTS                2068
#define IDC_BUTTONSRULES                2069
#define IDC_BUTTONSTART                 2070
#define IDC_BUTTONSVEGETATION           2071
#define IDC_BUTTONUSEACTIVATED          2072
#define IDC_BUTTONVOLUME                2073
#define IDC_CHECKACCESS                 2074
#define IDC_CHECKAUTOEDITSCAN           2076
#define IDC_CHECKDEBUGMODE              2079
#define IDC_CHECKEXPLORERFX             2082
#define IDC_CHECKEXPLORERMUSIC          2083
#define IDC_CHECKGAMEFX                 2084
#define IDC_CHECKGAMEMUSIC              2086
#define IDC_CHECKMAPPLAYEREXTEND        2088
#define IDC_CHECKOPENBOTTOM             2092
#define IDC_CHECKOPENTOP                2093
#define IDC_CHECKPLAYERINFO             2094
#define IDC_CHECKPORTRAITS              2095
#define IDC_CHECKSENDDEFRELOAD          2096
#define IDC_CHECKSHOWLAYERS             2097
#define IDC_CHECKSHOWSCREEN             2099
#define IDC_CHECKUSESHELL               2102
#define IDC_CHECKVERBOSEOBJECTS         2103
#define IDC_CHECKVIEWPORTBORDER         2104
#define IDC_COMBOICON                   2106
#define IDC_CTRLLANDSCAPE               2107
#define IDC_CURSORCOPY                  2108
#define IDC_DECOACCESS                  2109
#define IDC_EDITCOMMENT                 2110
#define IDC_EDITCTRLKEY1                2112
#define IDC_EDITCTRLKEY10               2113
#define IDC_EDITCTRLKEY11               2114
#define IDC_EDITCTRLKEY12               2115
#define IDC_EDITCTRLKEY2                2116
#define IDC_EDITCTRLKEY3                2117
#define IDC_EDITCTRLKEY4                2118
#define IDC_EDITCTRLKEY5                2119
#define IDC_EDITCTRLKEY6                2120
#define IDC_EDITCTRLKEY7                2121
#define IDC_EDITCTRLKEY8                2122
#define IDC_EDITCTRLKEY9                2123
#define IDC_EDITEDITORBITMAP            2124
#define IDC_EDITEDITORMUSIC             2125
#define IDC_EDITEDITORRICHTEXT          2126
#define IDC_EDITEDITORSCRIPT            2127
#define IDC_EDITEDITORSOUND             2128
#define IDC_EDITEDITORTEXT              2129
#define IDC_EDITEDITORZIP               2130
#define IDC_EDITFIX1                    2131
#define IDC_EDITFIX10                   2132
#define IDC_EDITFIX11                   2133
#define IDC_EDITFIX12                   2134
#define IDC_EDITFIX2                    2135
#define IDC_EDITFIX3                    2136
#define IDC_EDITFIX4                    2137
#define IDC_EDITFIX5                    2138
#define IDC_EDITFIX6                    2139
#define IDC_EDITFIX7                    2140
#define IDC_EDITFIX8                    2141
#define IDC_EDITFIX9                    2142
#define IDC_EDITINPUT                   2143
#define IDC_EDITLOG                     2145
#define IDC_EDITMAXPLAYERS              2146
#define IDC_EDITTEXT                    2157
#define IDC_EDITZOOM                    2158
#define IDC_EQUIPBUILDINGBTNS           2159
#define IDC_EQUIPBUILDINGLIST           2160
#define IDC_EQUIPBUILDINGSTC            2161
#define IDC_EQUIPBUILDUNITBTNS          2162
#define IDC_EQUIPBUILDUNITLIST          2163
#define IDC_EQUIPBUILDUNITSTC           2164
#define IDC_EQUIPBUYUNITBTNS            2165
#define IDC_EQUIPBUYUNITLIST            2166
#define IDC_EQUIPBUYUNITSTC             2167
#define IDC_EQUIPMATERIALBTNS           2168
#define IDC_EQUIPMATERIALLIST           2169
#define IDC_EQUIPMATERIALSTC            2170
#define IDC_EQUIPPLAYER1                2171
#define IDC_EQUIPPLAYER2                2172
#define IDC_EQUIPPLAYER3                2173
#define IDC_EQUIPPLAYER4                2174
#define IDC_EQUIPPLAYERALL              2175
#define IDC_EQUIPPLAYERSTC              2176
#define IDC_EQUIPREGENUNITBTNS          2177
#define IDC_EQUIPREGENUNITLIST          2178
#define IDC_EQUIPREGENUNITSTC           2179
#define IDC_EQUIPVEHICLEBTNS            2180
#define IDC_EQUIPVEHICLELIST            2181
#define IDC_EQUIPVEHICLESTC             2182
#define IDC_EQUIPWEALTHEDIT             2183
#define IDC_EQUIPWEALTHSPIN             2184
#define IDC_EQUIPWEALTHSTC              2185
#define IDC_FRAMECENTER                 2186
#define IDC_FRAMELARGEDESC              2189
#define IDC_FRAMESMALLDESC              2191
#define IDC_LISTANIMALS                 2192
#define IDC_LISTCREW                    2193
#define IDC_LISTDEFS                    2194
#define IDC_LISTENVIRONMENT             2195
#define IDC_LISTGOALS                   2196
#define IDC_LISTINEARTH                 2198
#define IDC_LISTMAGIC                   2199
#define IDC_LISTNESTS                   2200
#define IDC_LISTRULES                   2201
#define IDC_LISTSPECIFIEDDEFS           2202
#define IDC_LISTTYPE                    2203
#define IDC_LISTVEGETATION              2204
#define IDC_RADIODEFBYCHOICE            2205
#define IDC_RADIODETAILS                2206
#define IDC_RADIOLOCALONLY              2209
#define IDC_RADIOPLAYERS1               2210
#define IDC_RADIOPLAYERS2               2211
#define IDC_RADIOPLAYERS3               2212
#define IDC_RADIOPLAYERS4               2213
#define IDC_RADIOPREDEFINEDDEFS         2214
#define IDC_RADIOSYMBOLS                2218
#define IDC_RICHEDITDESC                2221
#define IDC_SLIDERAMPLITUDE             2222
#define IDC_SLIDERANIMALS               2223
#define IDC_SLIDERBUILDINGS             2224
#define IDC_SLIDERCLIMATE               2225
#define IDC_SLIDERCREW                  2226
#define IDC_SLIDEREARTHQUAKES           2227
#define IDC_SLIDERENVIRONMENT           2228
#define IDC_SLIDERGOALS                 2229
#define IDC_SLIDERGRAVITY               2230
#define IDC_SLIDERHEIGHT                2231
#define IDC_SLIDERHOMEBASEMAT           2232
#define IDC_SLIDERHOMEBASEPROD          2233
#define IDC_SLIDERINEARTH               2234
#define IDC_SLIDERINEARTHAMOUNT         2235
#define IDC_SLIDERKNOWLEDGE             2236
#define IDC_SLIDERMAGIC                 2237
#define IDC_SLIDERMATERIAL              2238
#define IDC_SLIDERMETEORITES            2239
#define IDC_SLIDERNESTS                 2240
#define IDC_SLIDERPERIOD                2241
#define IDC_SLIDERPHASE                 2242
#define IDC_SLIDERRAIN                  2243
#define IDC_SLIDERRANDOM                2244
#define IDC_SLIDERRULES                 2245
#define IDC_SLIDERSEASON                2246
#define IDC_SLIDERSMOKE                 2247
#define IDC_SLIDERTHUNDERSTORMS         2248
#define IDC_SLIDERTIMEADVANCE           2249
#define IDC_SLIDERVEGETATION            2250
#define IDC_SLIDERVEGETATIONAMOUNT      2251
#define IDC_SLIDERVEHICLES              2252
#define IDC_SLIDERVOLCANOES             2253
#define IDC_SLIDERWATERLEVEL            2254
#define IDC_SLIDERWIDTH                 2255
#define IDC_SLIDERWIND                  2256
#define IDC_SLIDERZOOM                  2257
#define IDC_SPINMAXPLAYERS              2261
#define IDC_STATICACCESS                2264
#define IDC_STATICAMPLITUDE             2265
#define IDC_STATICANIMALS               2266
#define IDC_STATICAUTHOR                2267
#define IDC_STATICBITMAP                2268
#define IDC_STATICBLOCK                 2269
#define IDC_STATICCLIMATE               2270
#define IDC_STATICCLIMATE2              2271
#define IDC_STATICCLIMATE3              2272
#define IDC_STATICCOMMENT               2274
#define IDC_STATICCREW                  2277
#define IDC_STATICCTRL1                 2278
#define IDC_STATICCTRL10                2279
#define IDC_STATICCTRL11                2280
#define IDC_STATICCTRL12                2281
#define IDC_STATICCTRL2                 2282
#define IDC_STATICCTRL3                 2283
#define IDC_STATICCTRL4                 2284
#define IDC_STATICCTRL5                 2285
#define IDC_STATICCTRL6                 2286
#define IDC_STATICCTRL7                 2287
#define IDC_STATICCTRL8                 2288
#define IDC_STATICCTRL9                 2289
#define IDC_STATICDIVIDER               2290
#define IDC_STATICEARTHQUAKES           2291
#define IDC_STATICEARTHQUAKES2          2292
#define IDC_STATICEARTHQUAKES3          2293
#define IDC_STATICENGINE                2294
#define IDC_STATICENVIRONMENT           2295
#define IDC_STATICERRORLOG              2296
#define IDC_STATICFRONTEND              2298
#define IDC_STATICGOALS                 2300
#define IDC_STATICGRAVITY               2301
#define IDC_STATICGRAVITY2              2302
#define IDC_STATICGRAVITY3              2303
#define IDC_STATICHEIGHT                2304
#define IDC_STATICICON                  2307
#define IDC_STATICINEARTHAMOUNTS        2308
#define IDC_STATICINEARTHTYPES          2309
#define IDC_STATICLANGUAGE              2313
#define IDC_STATICLOCATION              2316
#define IDC_STATICMAGIC                 2317
#define IDC_STATICMAPTYPE               2318
#define IDC_STATICMAXPLAYERS            2319
#define IDC_STATICMETEORITES            2321
#define IDC_STATICMETEORITES2           2322
#define IDC_STATICMETEORITES3           2323
#define IDC_STATICMUSIC                 2325
#define IDC_STATICNESTS                 2326
#define IDC_STATICPERIOD                2327
#define IDC_STATICPHASE                 2328
#define IDC_STATICPREVIEWFOR            2330
#define IDC_STATICPROMPT                2332
#define IDC_STATICRAIN                  2334
#define IDC_STATICRAIN2                 2335
#define IDC_STATICRAIN3                 2336
#define IDC_STATICRANDOM                2337
#define IDC_STATICRESOLUTION            2339
#define IDC_STATICRICHTEXT              2340
#define IDC_STATICRULES                 2341
#define IDC_STATICSCENARIOUSES          2342
#define IDC_STATICSCRIPT                2343
#define IDC_STATICSEASON                2344
#define IDC_STATICSEASON2               2345
#define IDC_STATICSEASON3               2346
#define IDC_STATICSELECTVIEW            2347
#define IDC_STATICSHOW                  2349
#define IDC_STATICSMOKE                 2351
#define IDC_STATICSMOKEHI               2352
#define IDC_STATICSMOKELOW              2353
#define IDC_STATICSOUND                 2354
#define IDC_STATICSOUNDEXPLORER         2355
#define IDC_STATICSOUNDGAME             2356
#define IDC_STATICSTATUS                2357
#define IDC_STATICTEXT                  2358
#define IDC_STATICTHUNDERSTORMS         2359
#define IDC_STATICTHUNDERSTORMS2        2360
#define IDC_STATICTHUNDERSTORMS3        2361
#define IDC_STATICTIMEADVANCE           2362
#define IDC_STATICTIMEADVANCE2          2363
#define IDC_STATICTIMEADVANCE3          2364
#define IDC_STATICTROUBLE               2365
#define IDC_STATICVEGETATIONAMOUNTS     2366
#define IDC_STATICVEGETATIONTYPES       2367
#define IDC_STATICVOLCANOES             2369
#define IDC_STATICVOLCANOES2            2370
#define IDC_STATICVOLCANOES3            2371
#define IDC_STATICVOLUME                2372
#define IDC_STATICWATERLEVEL            2373
#define IDC_STATICWIDTH                 2374
#define IDC_STATICWIND                  2375
#define IDC_STATICWIND2                 2376
#define IDC_STATICWIND3                 2377
#define IDC_STATICZIP                   2378
#define IDC_STATICZOOM                  2379
#define IDC_TABSCENARIO                 2380
#define IDC_VIEW                        2381
#define IDC_BUTTONEDITORPNG             2382
#define IDC_BUTTONSSKIPDEFS             2383
#define IDC_CHECKMMTIMER                2386
#define IDC_CHECKPOINTFLTR              2387
#define IDC_CHECKNOALPHAADD             2389
#define IDC_EDITEDITORPNG               2391
#define IDC_LISTSKIPDEFS                2392
#define IDC_RADIOBITS16                 2395
#define IDC_RADIOBITS32                 2396
#define IDC_SLIDERSKIPDEFS              2397
#define IDC_STATICPNG                   2398
#define IDC_STATICBITDEPTH              2399
#define IDC_STATICSKIPDEFS              2400
#define IDC_BITMAPGRAVITY               2405
#define IDC_COMBO_LANGUAGE              2407
#define IDC_EDITPWD                     2408
#define IDC_EDITCUID                    2409
#define IDC_EDITNICK                    2410
#define IDC_EDITWEBCODE                 2411
#define IDC_STATICCUID                  2412
#define IDC_STATICFULLNAME              2413
#define IDC_STATICNICK                  2414
#define IDC_STATICKEYFILENAME           2415
#define IDC_STATICGFXENGINE             2416
#define IDC_STATICWEBCODE               2416
#define IDC_EDITFULLNAME                2417
#define IDD_ABOUT                       3000
#define IDD_EXPLORER                    3002
#define IDD_IDSELECT                    3003
#define IDD_INPUT                       3004
#define IDD_INTRO                       3005
#define IDD_LICENSE                     3006
#define IDD_LOG                         3007
#define IDD_MESSAGE                     3008
#define IDD_NETSTART                    3009
#define IDD_PAGEDEVELOPER               3010
#define IDD_PAGEEDITOR                  3011
#define IDD_PAGEENVIRONMENT             3012
#define IDD_PAGEGAME                    3013
#define IDD_PAGEGRAPHICS                3015
#define IDD_PAGEKEYBOARD                3016
#define IDD_PAGELANDSCAPE               3017
#define IDD_PAGEPLAYERSTART             3019
#define IDD_PAGEPROGRAM                 3020
#define IDD_PAGESOUND                   3021
#define IDD_PAGEWEATHER                 3022
#define IDD_PLAYER                      3023
#define IDD_PROMOTION                   3024
#define IDD_REGISTRATION                3026
#define IDD_SCENARIO                    3027
#define IDD_SCENARIODEFINITIONS         3028
#define IDD_TYPESELECT                  3029
#define IDM_HELP_ABOUT                  4000
#define IDM_HELP_WEBSITE                4003
#define IDM_MAIN                        4004
#define IDM_OPTIONS_OPT                 4005
#define IDM_OPTIONS_REG                 4006
#define IDN_DEFFOLDER                   5001
#define IDN_DEFINITION                  5002
#define IDN_FOLDER                      5003
#define IDN_PLAYER                      5005
#define IDN_RICHTEXT                    5006
#define IDN_SCENARIO                    5007
#define IDN_SCRIPT                      5008
#define IDN_SOUND                       5009
#define IDN_TEXT                        5010
#define IDN_PNG                         5011
#define IDR_MAINFRAME                   6007
#define IDM_HELP_ONLINEDOCS             32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1329
#define _APS_NEXT_SYMED_VALUE           141
#endif
#endif
