set(FILE_LIST
src/C4Attributes.h
src/C4Breakpoint.h
src/C4Chrono.cpp
src/C4Chrono.h
src/C4ForwardDeclarations.h
src/C4Math.cpp
src/C4Math.h
src/C4Strings.cpp
src/C4Strings.h
src/CStdFile.cpp
src/CStdFile.h
src/Standard.h
src/StdAdaptors.h
src/StdBuf.cpp
src/StdBuf.h
src/StdCompiler.cpp
src/StdCompiler.h
src/StdConfig.h
src/StdFile.cpp
src/StdFile.h
src/StdGzCompressedFile.cpp
src/StdGzCompressedFile.h
src/StdHelpers.h
src/StdOSVersion.cpp
src/StdOSVersion.cpp
src/StdSha1.h
)
