name: 'Test Build Configurations'

on:
  push:
    branches: ['build-test*']

defaults:
  run:
    shell: bash

jobs:
  generate-ci-config:
    name: Generate CI Configuration
    uses: './.github/workflows/ci-config.yml'
    with:
      config-file: autobuild/config_tests.toml
      generation-script: autobuild/generate_test_configs.py

  Autobuild:
    needs: [generate-ci-config]
    uses: './.github/workflows/build.yml'
    with:
      matrix: ${{ needs.generate-ci-config.outputs.matrix }}
