name: Validate C4Script functions

on:
  push:
    branches: [ 'master' ]

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout legacyclonk repo
        uses: actions/checkout@v2

      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          repository: legacyclonk/lcdocs
          path: lcdocs

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: .github/workflows/C4ScriptDocAnalyzer/package-lock.json

      - name: Install dependencies
        run: |
          npm install
          sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends xsltproc python-libxml2 gettext -y

      - name: Build function list
        run: make -C lcdocs -j$(nproc)

      - name: Copy generated Functions.txt
        run: cp lcdocs/Functions.txt .github/workflows/C4ScriptDocAnalyzer/lcdocs_functions.txt

      - name: Run analyze script
        id: analyze
        run: node .github/workflows/C4ScriptDocAnalyzer/index.js
        continue-on-error: false

