name: Validate C4Script functions

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout legacyclonk repo
        uses: actions/checkout@v6

      - name: Checkout docs repo
        uses: actions/checkout@v6
        with:
          repository: legacyclonk/lcdocs
          path: lcdocs

      - name: "Ubuntu 18.04: Setup chroot"
        run: |
          curl -L https://github.com/legacyclonk/ubuntu-1804-x86-chroot/releases/download/2022-05-19/chroot.tar.xz | sudo tar -xJ
          curl -L https://raw.githubusercontent.com/legacyclonk/ubuntu-1804-x86-chroot/master/setup_chroot.sh | sudo bash -e -
          sudo mkdir -p chroot/$PWD
          sudo mount --bind . chroot/$PWD
          echo "CHROOT=$PWD/.github/workflows/Linux-x86-chroot.sh" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: 'npm'
          cache-dependency-path: .github/workflows/C4ScriptDocAnalyzer/package-lock.json

      - name: Install dependencies
        run: |
          (cd .github/workflows/C4ScriptDocAnalyzer && npm install)
          $CHROOT sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends xsltproc python-libxml2 gettext -y

      - name: Build function list
        run: $CHROOT make -C lcdocs -j$(nproc)

      - name: Copy generated Functions.txt
        run: cp lcdocs/Functions.txt .github/workflows/C4ScriptDocAnalyzer/lcdocs_functions.txt

      - name: Run analyze script
        id: analyze
        run: node .github/workflows/C4ScriptDocAnalyzer/index.js
        continue-on-error: false

